# Generated by the Chameleon Platform

source 'https://rubygems.org'

gem 'rails', '3.2.2'

gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'omniauth'

gem 'dm-rails', '~> 1.2.0'
gem 'dm-serializer'
gem 'dm-mysql-adapter'
gem 'mongoid', '2.4.7'
gem 'bson_ext'
# gem 'unicorn'
# gem 'capistrano'