Rails.application.config.middleware.use OmniAuth::Builder do
  # If configured for third party auth...
  # provider :twitter ...
  # provider :github ...

  require Rails.root.join('lib', 'omniauth', 'strategies', 'password.rb')
  provider :password
end